# Generated by Django 3.0.3 on 2021-11-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20211125_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
